{
 "title": "Log Monitoring & Alerting System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(request_count_total[1m])) by (endpoint, status)",
     "legendFormat": "{{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "p95 {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_latency_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "p50 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Log Anomalies Detected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(logs_processed_total{severity!=\"\"}[1m])) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Active Unresolved Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_alerts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"log-monitor-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}